### ISSUE TITLE
Erro ao abrir janela de exibição 

### ISSUE THREAD

**Issue by IvanCampelo22** [DeeDee100/hash_password#5]
Juntei as funções de geração de hash e de criar uma nova janela, no entanto, abre a janela, mas não exibe nada e apresenta o erro 'Application' object has no attribute 'encode'

Combinando as funções: 
 ```
def combineFunc(self, *funcs):
        def combinedFunc(*args, **kwargs):
            for f in funcs:
                f(*args, **kwargs)
        return combinedFunc
```
Trazendo elas para o tkinter

`self.generator_hash["command"] = self.combineFunc(self.hash_Password, self.hashe_exbition)`

**Comment by DeeDee100** [comment]
Corrigido no PR 6 :D
